spring:
  servlet:
    multipart:
      max-file-size: 5TB
      max-request-size: 15TB

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.11.11:3150/mytest2
    username: projectg3
    password: 1234

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html

server:
  port: 3150

---

spring:
  config:
    activate:
      on-profile: "jpa"
  datasource:
    url: jdbc:mariadb://127.0.11.11:3150/mytest2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: "prod2"